skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lp = "29UGDKvnsZMAju1XvduUY3Ksqpx1MMuNzRpa3w584P9t"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
